### ISSUE TITLE
Add support for pnpm in nodejs buildpack

### ISSUE THREAD

**Issue by sidvishnoi** [GoogleCloudPlatform/buildpacks#193]
`gcloud functions deploy` doesn't make use of `pnpm-lock.yaml` and only supports yarn and npm.
For this reason, we need to maintain both `package-lock.json` (prod) and `pnpm-lock.yaml` (dev; due to better monorepo support) in our project. Please consider adding support for pnpm to the nodejs buildpack.

**Comment by Snugug** [comment]
Has there been any movement on this? It's something we're looking for as well.

Thanks!

**Comment by segevfiner** [comment]
No support for pnpm also breaks when using in a pnpm workspace with `workspace:` dependencies which is a pnpm specific syntax. But for those to work fully there needs to be full monorepo support, but having them just in dev dependencies and bundling could still be workable if the buildpack knew to use `pnpm`.

**Comment by moekify** [comment]
I also think this would be a great enhancement!

**Comment by jpreynat** [comment]
Big +1 on this one.
We recently switched our monorepo application to `pnpm`, and support for it in the NodeJS buildpack would make sure that we are using the proper dependencies in our Cloud Run applications.
Right now, `npm` is only using our `package.json` file, so we are never sure if or when things are going to break because of a dependency update.

**Comment by matthewrobertson** [comment]
Support for pnpm in the Node.js buildpacks landed last week. If your project includes a `pnpm-lock.yaml` the builpacks will install pnpm and use it to manage your application dependencies and run any scripts you have configured in `package.json`.  There is a working [sample app here](https://github.com/GoogleCloudPlatform/buildpack-samples/tree/master/sample-node-pnpm).

One caveat for Google Cloud Functions: you must have include `@google-cloud/functions-framework` as an explicit dependency.

Please give it a try an let me know if you have any feedback.

**Comment by buzzb0x** [comment]
Hey folks, my buildpack build process broke after I refactored to turn my repo into a monorepo with pnpm. Could this be related to the pnpm support, as someone mentioned the special `workspace:` syntax?

I'm running the build command from the package directory inside the monorepo and getting this output:

```
[builder] failed to build: (error ID: ebe03a99):
[builder] installing pnpm dependencies: (error ID: 8622936f):
[builder] Recreating /workspace/node_modules
[builder]  ERR_PNPM_OUTDATED_LOCKFILE  Cannot install with "frozen-lockfile" because pnpm-lock.yaml is not up to date with package.json
[builder] 
[builder] Note that in CI environments this setting is true by default. If you still need to run install in such cases, use "pnpm install --no-frozen-lockfile"
[builder] 
[builder]     Failure reason:
[builder]     specifiers in the lockfile ({"@aws-sdk/client-s3":"^3.418.0","@fastify/formbody":"^7.4.0","dotenv":"^16.3.1","fastify":"^4.23.2","@types/node":"^18.17.19","tsc-alias":"^1.8.8","tsconfig-paths":"^4.2.0","tsx":"^3.12.10","typescript":"^5.2.2"}) don't match specs in package.json ({"@types/node":"^18.17.19","tsc-alias":"^1.8.8","tsconfig-paths":"^4.2.0","tsx":"^3.12.10","typescript":"^5.2.2","@aws-sdk/client-s3":"^3.418.0","@fastify/formbody":"^7.4.0","@react-email/render":"0.0.7","@virtuoso/email-templates":"workspace:^","dotenv":"^16.3.1","fastify":"^4.23.2","libphonenumber-js":"^1.10.50","resend":"^2.0.0"})
```

**Comment by alexandercerutti** [comment]
> Support for pnpm in the Node.js buildpacks landed last week. If your project includes a `pnpm-lock.yaml` the builpacks will install pnpm and use it to manage your application dependencies and run any scripts you have configured in `package.json`. There is a working [sample app here](https://github.com/GoogleCloudPlatform/buildpack-samples/tree/master/sample-node-pnpm).
> 
> One caveat for Google Cloud Functions: you must have include `@google-cloud/functions-framework` as an explicit dependency.
> 
> Please give it a try an let me know if you have any feedback.

@matthewrobertson it worked. However, the fact that, after over **two years**, official documentation doesn't say **anything** about this **AND** about the fact that, in case of monorepos, we need to create a `pnpm-lock.yaml` for each monorepo package, is a f*****g shame. Same is valid for `.npmrc`.

Documentation only reports in [Handling Dependencies](https://firebase.google.com/docs/functions/handle-dependencies?authuser=8&lang=nodejs) page about the pnpm usage if a `pnpm-lock.yaml` is found, but it wasn't clear that we needed to have a `pnpm-lock.yaml` for each project being deployed in the `firebase.json`.

In order to make things automatic through a Github Action, I set an step that does this.

```
      - name: Prepare projects for deployment
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GH_TOKEN_FOR_PRIVATE_REGISTRY_ACCESS }}
        run: |
          for dir in $(cat firebase.json | jq -r ".functions[].source"); do
            pnpm -C $dir install --ignore-workspace
          done
```

Where `--ignore-workspace` is an undocumented feature of `pnpm` (see [discussion](https://github.com/orgs/pnpm/discussions/4735))

**Comment by kdawgwilk** [comment]
I also just learned that `pnpm install` in the buildpack also install dev deps in the production container?!

We are going to attempt to create a `.npmrc` file in the directory that goes to cloud build with 
```
production=true
```
That pnpm will respect and not install dev deps
