### ISSUE TITLE
Node 18 takeback?

### ISSUE THREAD

**Issue by waded** [GoogleCloudPlatform/buildpacks#248]
Had a project previously built for Heroku that I started deploying to Cloud Run October 2022 or so using `gcloud run deploy` that specified 

```
  "engines": {
    "node": "18.x"
  },
 ```

in package.json.

And as of Nov 28 this was building (and running) correctly. Here's a relevant portion of build log from the 28th:

```
===> BUILDING
[builder] === Node.js - Runtime (google.nodejs.runtime@1.0.0) ===
[builder] 2022/11/28 19:43:57 [DEBUG] GET https://dl.google.com/runtimes/ubuntu1804/nodejs/version.json
[builder] Installing Node.js v18.12.1.
[builder] 2022/11/28 19:43:57 [DEBUG] GET https://dl.google.com/runtimes/ubuntu1804/nodejs/nodejs-18.12.1.tar.gz
[builder] === Node.js - NPM (google.nodejs.npm@1.0.0) ===
[builder] Installing application dependencies.
```

but as of Nov 29 the same build receives an error:

```
===> BUILDING
[builder] === Node.js - Runtime (google.nodejs.runtime@1.0.0) ===
[builder] 2022/11/29 23:33:20 [DEBUG] GET https://dl.google.com/runtimes/ubuntu1804/nodejs/version.json
[builder] Failure: (ID: 9cd081f9) invalid Node.js version specified: failed to resolve version matching: 18.x
[builder] --------------------------------------------------------------------------------
[builder] Sorry your project couldn't be built.
[builder] Our documentation explains ways to configure Buildpacks to better recognise your project:
[builder]  -> https://github.com/GoogleCloudPlatform/buildpacks/blob/main/README.md
[builder] If you think you've found an issue, please report it:
[builder]  -> https://github.com/GoogleCloudPlatform/buildpacks/issues/new
```

After looking around a bit, I couldn't find standard documentation of max version (which is an issue on its own - if LTS is not supported docs should say so.) I did find closed issues stating that Node 18 was not working on Ubuntu 18 and so was not supported, but they all predate it seemingly working as shown above.

I can probably regress this project to Node 16, but I've another I'd like to move over that won't be so easy. Besides heading off unsupported conditions a bit earlier through docs, it'd be helpful to know when 18 will be supported again.

**Comment by matthewrobertson** [comment]
This my fault, I updated the supported version range to exclude Nodejs18 because I was under the impression that our base image didn't support it. I could have sworn that I tested this right after Nodejs18 was released and I discovered that it didn't work because Ubuntu18 ships an unsupported version of glibc. Maybe something changed...

For now, there are a few things to note:

1. The Nodejs18 tarballs are still available, the buildpacks are just refusing the resolve the version constraint, so if you pin down to the patch you can still use Nodejs18:

    ```
    "engines": {
        "node": "18.12.0"
      },
    ```

2. We are working on publishing a new builder based on Ubuntu 22.04, which will definitely support Node.js 18. We recommend everyone upgrades when it becomes available in the next couple weeks.

3. I will spend some time investigating Nodejs18 compatibility with Ubuntu 18.04. If it is actually supported, I can quickly update the version manifest to allow resolving constraints like `18.x` again.

**Comment by matthewrobertson** [comment]
Here is the commit where Node.js bumped the minimum glibc/Ubuntu versions in their BUILDING.md: https://github.com/nodejs/node/commit/3671cc043233d9e75994ce17abb050ee0581dce0

**Comment by matthewrobertson** [comment]
IIRC when we originally tested Node.js 18 it didn't compile, so the fact that these tarballs got published suggests something changed.

**Comment by waded** [comment]
Thanks for tip 1 (pin down to the patch), that should suffice for a few weeks for this particular project.

In case it's helpful in working back to what happened, it appears first successful build I had targeting "18.x" was on October 25:

```
===> BUILDING
[builder] === Node.js - Runtime (google.nodejs.runtime@1.0.0) ===
[builder] 2022/10/25 13:25:10 [DEBUG] GET https://dl.google.com/runtimes/ubuntu1804/nodejs/version.json
[builder] Installing Node.js v18.11.0.
[builder] 2022/10/25 13:25:10 [DEBUG] GET https://dl.google.com/runtimes/ubuntu1804/nodejs/nodejs-18.11.0.tar.gz
```

**Comment by u12206050** [comment]
I've tried now with quite a number of different explicit node versions but all of them are getting 404 during build:

**18.2.1**
```
Failure: (ID: 7fdca554) fetching https://dl.google.com/runtimes/ubuntu1804/nodejs/nodejs-18.2.1.tar.gz returned HTTP status: 404
```

**18.12.x**
```
Step #0 - "Buildpack": 2023/01/14 07:29:22 [DEBUG] GET https://dl.google.com/runtimes/ubuntu1804/nodejs/version.json
Step #0 - "Buildpack": Failure: (ID: ae212299) invalid Node.js version specified: failed to resolve version matching: 18.12.x
```

**18.13.0**
```
Failure: (ID: 8be17978) fetching https://dl.google.com/runtimes/ubuntu1804/nodejs/nodejs-18.13.0.tar.gz returned HTTP status: 404
```

**Comment by smsohan** [comment]
We're looking into it.

**Comment by MontyCarter** [comment]
@u12206050 What has happened here is that we constrained the set of versions that we download and publish, as well as the versions available when using version resolution to select a version.

`18.2.1` didn't work because a nodejs v18.2.1 was never released.
`18.12.x` didn't work because it requires version resolution, and `>=18.0.0 < 19.0.0` was removed from the set of resolvable versions.
`18.13.0` didn't work because this was released after we removed `>=18.0.0 < 19.0.0` from the set of versions to download and publish.

The latest version that we have downloaded and published is `18.12.1`.  Using this as the version specifier is currently working to allow deployments.

With all that said, we are close to having the new Ubuntu 22.04 builder available.

**Comment by jama22** [comment]
We also just released the Ubuntu22 builders for our buildpacks. I'll be doing a longer writeup for it soon, but you can give it a try with pack: `pack build --builder=gcr.io/buildpacks/builder:google-22 <image name> `

or with Cloud Build:
```
gcloud builds submit \
    --pack builder=gcr.io/buildpacks/builder:google-22,image=<region>.pkg.dev/<project>/<repository>/<image-name>
```

**Comment by jama22** [comment]
You can check the write up announcing the Ubuntu 22 builder here https://github.com/GoogleCloudPlatform/buildpacks/discussions/271 

Closing the issue since we now have a path for ya'll to use Node.js 18. Please feel free to open a new issue  if you find that Node.js 18 still doesn't quite work on the new `google-22` builders
