### ISSUE TITLE
how to check the base image of the image built using buildpacks?

### ISSUE THREAD

**Issue by Divyashet66** [GoogleCloudPlatform/buildpacks#319]
Hi, I have built one nodejs image by using buildpacks, I want to check which version of  base node image is present in the image, how should I check?

I tried a lot, I'm not able to find..please help

**Comment by jama22** [comment]
Hey @Divyashet66 , this doesn't seem to be a bug, but a general question around buildpacks. We'd really appreciate it if you ask these types of questions in the [Discussions](https://github.com/GoogleCloudPlatform/buildpacks/discussions) section of our project because it helps with issue triage and if other people have the same question they can find the information there. Also, don't remove/ignore the bug template; it helps us get crucial information to debug incoming issues. We want to respect your time, so please respect ours. 

That being said, you can likely find the information you're looking for by using `docker image inspect <image name>`. If you look at the output, you can find which run image was used (`gcr.io/buildpacks/google-22/run`)

If you need to know  the specific tag that was being used, it might be easier to keep track of this through the build logs.

Would love to help you if you have follow up questions. Please ask us in [Discussions](https://github.com/GoogleCloudPlatform/buildpacks/discussions)
