### ISSUE TITLE
Serve static files from `public` via nginx in PHP runtime

### ISSUE THREAD

**Issue by iamacarpet** [GoogleCloudPlatform/buildpacks#323]
**Is your feature request related to a problem? Please describe.**

It currently isn't possible to serve static asset files from the `public` folder in your application via nginx in the container generated by the buildpack.

This isn't a problem on App Engine, as it has it's own method of serving static files from different infrastructure.

On Cloud Run, these files need to be served by the instance and this currently isn't possible, as far as I can tell.

**Describe the solution you'd like**

The option to use a nginx configuration where if a request path matches a file in the `public` folder, that file is served instead of using the default dynamic route to `public/index.php`.

**Describe alternatives you've considered**

Serving the files inside PHP, which is slow, inefficient and not considered to be "safe" from a security perspective.

**Additional context**

In a PHP project, Laravel for instance, you have a folder structure like this:

```
- app
- config
- routes
- public
  - index.php
  - css
    -main.css
  - img
    - ...
  - js
    - ...
```

It's a poor representation, but the idiomatic setup for running the application is with a web server (e.g. nginx) routing all dynamic requests to `public/index.php` (which the current buildpack is doing).

However, the usual idiomatic behaviour for a PHP environment is for that web server (e.g. nginx) to check inbound request paths to see if they match a file inside the public folder (e.g. `/css/main.css -> public/css/main.css`) and if it exists, serve the file instead.

This is idiomatic behaviour because the usual PHP workflow expects those css/js/image files to be versioned & deployed alongside the application & served alongside it - external hosting like Firebase or Cloud Storage doesn't really fit the workflow, mainly because you'd lose the main benefit of having service versions, both in App Engine & Cloud Run, that can be tied to Git version control revisions, if only half of your application was deployed that way, but the css/js/image files that are also versioned in that same Git repository, have to be managed independently on Firebase / Cloud Storage.

My workflow when writing a Go application would be much the same, except unlike PHP which requires an external web server (e.g. nginx), Go is it's own web server, so you configure static asset routing within the application routing, e.g.:

```go
package main

import (
    ....
)

func main() {
    ....

    sfs := http.FileServer(http.Dir("/srv/resources/static"))
    r.PathPrefix("/static/").Handler(negroni.New(
        negroni.Wrap(http.StripPrefix("/static/", sfs)),
    ))

    ....

    port := os.Getenv("PORT")
    if port == "" {
        port = "8080"
        log.Printf("Defaulting to port %s", port)
    }

    log.Printf("Listening on port %s", port)
    if err := http.ListenAndServe(":"+port, nil); err != nil {
        log.Fatal(err)
    }
}
```

Which works fine, as the buildpacks are bundling the static files into the Docker container image created, as they are doing on PHP.

Since PHP isn't designed to be it's own web server, serving the files via PHP isn't really very easy, performant or practical for a production application, and adjusting the nginx config on the PHP buildpack isn't supported, AFAIK.

**Comment by iamacarpet** [comment]
@sl0wik have you come across this same problem when using Cloud Run with these buildpacks, or am I barking up the wrong tree here?

**Comment by iamacarpet** [comment]
Similar issues flagged by other users:

https://github.com/GoogleCloudPlatform/buildpacks/issues/234

https://github.com/GoogleCloudPlatform/buildpacks/issues/235

**Comment by jama22** [comment]
Thanks for the detailed feature request @iamacarpet !

I think a good first step here might be to give users the ability to provide a custom nginx config so you can serve those static files.

Something else to consider: if the nginx rules are relatively repeatable for PHP website, maybe we should just make them the default nginx config when using the PHP buildpack so folks don thave to provide a custom nginx config every time

**Comment by kennethye1** [comment]
[8d74970](https://github.com/GoogleCloudPlatform/buildpacks/commit/8d7497071b49a4fa51f1b40ed931c4ca550e2bad)  lets you specify `GOOGLE_CUSTOM_NGINX_CONFIG="custom-nginx.conf"` as an override.

**Comment by iamacarpet** [comment]
Thanks @jama22 ,

> Something else to consider: if the nginx rules are relatively repeatable for PHP websites / frameworks like Laraval, maybe we should just make them the default nginx config when using the PHP buildpack so folks don't have to provide a custom nginx config every time. Would you say that serving off public/ is pretty common?

Yes, I would say for every web application with assets (so not just an API), this is an expectation, so I agree, it would be useful for this either to be a default, or a more easily selectable option.

I think @sl0wik has said elsewhere that they are doing purely API deployments, so it may be why you've not got firm feedback on this in the past.

@kennethye1 thank you for sorting this - are you able to clarify what context the custom nginx config runs?

It it an `include` within a larger default config, or is it provided as a whole to nginx on startup as it's global config?

If it's the latter, I think it would be important to establish what the default configuration looks like, so we can customise it.

Is it documented anywhere, or am I best to build a constainer with the default config & dump it?

**Comment by kennethye1** [comment]
@iamacarpet It'll start the custom nginx config at startup, not as an include statement currently.

**Comment by sl0wik** [comment]
@iamacarpet Sorry for the late reply.

My conclusion on this matter was to not use Cloud Run to serve static files. Cloud Run should be a code executor, not CDN. App Engine does it because it has a built-in CDN (probably LB behind the scenes that redirects static traffic to some storage with CDN at the top).

I would resolve it on CI level. Copy static to Firebase Hosting, or Storage.

**Comment by sonnysasaka** [comment]
I recently came across this issue and this was blocking my Laravel deployment. Eventually I found a hack that works: use the `nginx-app.conf` in the repo root like this: https://gist.github.com/sonnysasaka/f3fab0c269891a3654d935dff14b0d63

I agree with an [earlier comment](#issuecomment-1628518464) think that Google should make this more easily supported rather expecting users to come up with a workaround like this.

For a longer term fix, I would suggest that GCP buildpacks add a flag in app.yaml like `serves_static_files` so that users can easily turn on this flag. The justification is that this is a very common PHP use case nowadays. I prefer a flag rather than enabling it by default since there are also many cases where deployment wants to hide files from public.

**Comment by sonnysasaka** [comment]
I made an attempt to add this flag: https://github.com/GoogleCloudPlatform/buildpacks/pull/386, please take a look if this approach is fine.

**Comment by safiyullahmohideen** [comment]
Hi,

I checked out your workaround solution by changing nginx.app.config.But only static files serving only working.While calling AJAX POST response "405 Not Allowed from nginx server".

 $.ajax({
                type: "POST",
                url: "test.php",                
                success: function (data) {
                    alert(data)
                },
                error: function(data){
                   alert(JSON.stringify(data))
                }
            })
Not working using your workaround solution
Can you please tell solution for that.

**Comment by safiyullahmohideen** [comment]
@sonnysasaka Thanks for your reply.I check out your workaround solution, both static file and php working in php 8.2 GAE.But I have one doubt ,if we changed nginx-app.config files means , any security issue will come?Bcoz, GAE need to change this one.

Then one more thing,where can we find our app ngnix-app.config files in GAE.

**Comment by sonnysasaka** [comment]
@safiyullahmohideen 

> @sonnysasaka Thanks for your reply.I check out your workaround solution, both static file and php working in php 8.2 GAE.But I have one doubt ,if we changed nginx-app.config files means , any security issue will come?Bcoz, GAE need to change this one.

I can't be sure about security. But generally the more we "eject" from the default the more it goes into the gray area of unsupported and may break whenever they change the default. I recommend that eventually this be supported by GAE. @jama22 Please take a look if this proposal makes sense: https://github.com/GoogleCloudPlatform/buildpacks/pull/386. Otherwise PHP on GAE usefulness will be very limited to API-only kind of apps although PHP is more popular for full stack apps.

> Then one more thing,where can we find our app ngnix-app.config files in GAE.

Not sure if I understand this question. If you were able to test it, that means you knew where to put it in your GAE app? It should be put as `nginx-app.conf` in the root of your app folder, as documented here: https://cloud.google.com/appengine/docs/flexible/php/runtime#v7.4-and-later.

**Comment by iamacarpet** [comment]
@sonnysasaka I've ping'd @jama22 and @kennethye1 about this outside of GitHub.

> Otherwise PHP on GAE usefulness will be very limited to API-only kind of apps although PHP is more popular for full stack apps.

I think on GAE (flexible environment and standard environment), you can handle this by using entries for the static files in `app.yaml`, i.e.:

```yaml
runtime: php81

automatic_scaling:
  max_concurrent_requests: 2

entrypoint: serve --workers=2 public/index.php

inbound_services:
- warmup

handlers:
- url: /favicon.ico
  static_files: public/favicon.ico
  upload: public/favicon.ico

- url: /robots.txt
  static_files: public/robots.txt
  upload: public/robots.txt

- url: /fonts
  static_dir: public/fonts

- url: /css
  static_dir: public/css

- url: /js
  static_dir: public/js

- url: .*
  secure: always
  script: auto
```

This is for the standard environment, but my understanding is something very similar should work for flex.

That being said, it is my understanding that the server-less team intend to push everything towards Cloud Run, as the most actively developed and feature rich product - and to be fair, with good reason, it is fantastic.

Your point still stands and I fully agree with you, I would just re-word it as:

> Otherwise PHP on Cloud Run's usefulness will be very limited to API-only kind of apps, although PHP is more popular for full stack apps.

I've re-stated this privately as well, as I think it's something that is likely stopping PHP developers from adopting these server-less products, as it introduces a lot of extra friction when getting started, which is likely to put most people off - especially considering Amazon's server-less products offer a more "traditional" PHP runtime environment as standard, even though both the server-less offering & the runtime setup is inferior in it's implementation.

**Comment by sonnysasaka** [comment]
Hi @iamacarpet,

> I think on GAE (flexible environment and standard environment), you can handle this by using entries for the static files in app.yaml, i.e.:

I think this only works on standard environment (tried and did not work on flex), the new PHP runtimes are all migrated to using GoogleCloudPlatform/buildpacks, which looks like what you are using too on Cloud Run. If that's the case, https://github.com/GoogleCloudPlatform/buildpacks/issues/323#issuecomment-1962773865 could also work for you. And my PR https://github.com/GoogleCloudPlatform/buildpacks/pull/386 has been merged by @kennethye1 as well so in a bit we don't need `nginx-app.conf` workaround but just set `NGINX_SERVES_STATIC_FILES` and it should solve the common Laravel set up (both App Engine flex or Cloud Run with this buildpacks).

So for now this unblocks my project (and yours too, assuming you use this buildpacks and run Laravel). If you need the more generic "run php if exists and fall back to serve static files", the workaround https://github.com/GoogleCloudPlatform/buildpacks/issues/323#issuecomment-1967355947 should work as confirmed by @safiyullahmohideen.

**Comment by iamacarpet** [comment]
Thanks for the update @sonnysasaka !

Glad to hear thanks to PR #386 that this is becoming an easier to configure option.

I do still feel like this should be the default, with a config option to turn it off instead - what are your thoughts?

**Comment by sonnysasaka** [comment]
@iamacarpet setting this `NGINX_SERVES_STATIC_FILES` as default will affect the behavior of existing deployments, and some of them may rely on the old behavior so it's safe to store internal data in the same dir (or subdir) of the front controller `index.php`, e.g.:

```
root
- index.php (front controller)
- internal-data.csv
- secret.txt
- sqlite-data.db
```

This deployment may have assumed and tested that it's safe to store internal data there, but the change in serving static files will change that.

I agree that it's better for this to be the default (because more common for PHP), but unfortunately because this product started without it, some deployments might already rely on the old behavior and it's risky to change that. I think with how it is currently, it's safer to let this off by default, but make it easy and obvious (e.g. document it [here](https://cloud.google.com/docs/buildpacks/php)) how to enable it.

Anyway that's just my opinion as a user, product decision should go back to @jama22 or @kennethye1.

**Comment by jama22** [comment]
Hey folks, sorry for being a bit late to the party. Thanks to @sonnysasaka for contributing this change, I really appreciate the time and energy you've taken to improve the PHP runtime 🥳 

I'll also have to agree with @sonnysasaka. I'm wary of making changes to buildpack defaults as it can be seen as a breaking change to people who rely on that behavior. I did something similar in the past with the Node runtime and it didn't work out well (see #287) 

Going to close this issue as the merged PR seems to have addressed the original issue request.
