### ISSUE TITLE
cache the downloaded deps for go modules

### ISSUE THREAD

**Issue by winmillwill** [GoogleCloudPlatform/buildpacks#83]
Apologies if I've missed some obvious configuration or some reason why this isn't feasible. IIUC part of the value added proposition of buildpacks is that the different buildpacks can cache their outputs and reuse them when the inputs don't change. When running pack twice in a row on my laptop, without changing anything on disk, the dependencies are downloaded each time.

**Comment by di** [comment]
@winmillwill Can you provide a minimal example? Which buildpack are you using?

**Comment by lukasberger** [comment]
We're not currently caching the modules or GOCACHE in the go.build buildpack (which I assume you're referring to since the gomod buildpack isn't used in the general builder). We used to have the latter but it was [removed](https://github.com/GoogleCloudPlatform/buildpacks/commit/1d340e9cfb2fb2654f2b68472cf30f8098ca757f) due unbounded growth. We should look into this.

**Comment by winmillwill** [comment]
@di seems like the issue is known, but here's a minimal example https://gist.github.com/winmillwill/8df0b9ae932dd20a2657641b7f9b36be

**Comment by matthewrobertson** [comment]
This is fixed now. We use the go.mod file as a cache key, so if you change it we will bust the cache.
