### ISSUE TITLE
Add Java Command Line Args At Runtime

### ISSUE THREAD

**Issue by adamzr** [GoogleCloudPlatform/buildpacks#88]
I want to add command line args to the entrypoint based on runtime environment variables. For example, right now my Java application runs as `java -classpath . org.springframework.boot.loader.JarLauncher`. I want to expose an environment variable to the Docker image called JAVA_OPTS and have the value of that added to that command. So, for example if JAVA_OPTS is set to `-javaagent:myagent.jar` then the command becomes `java -classpath . org.springframework.boot.loader.JarLauncher -javaagent:myagent.jar`. Is it possible to do this?

**Comment by jamesward** [comment]
I think you can do this by having a custom `Procfile` with something like:
```
web: java -classpath . org.springframework.boot.loader.JarLauncher $JAVA_PARAMS
```
Note that I used `JAVA_PARAMS` since `JAVA_OPTS` usually gets used for other things.

**Comment by briandealwis** [comment]
Just in case you're looking to do this because of difficulty in passing in arguments in the past… 

We recently updated the GCP Buildpacks to use Cloud Native Buildpacks `lifecycle` 0.9 / Platform API 0.4 which reworks how processes are represented.  Buildpacks-built images now behave like normal container images, such that you you can just provide command-line arguments using the normal mechanisms.  For example:
```console
$ cat src/main/java/Main.java
public class Main {
  public static void main(String[] args) {
    for(String arg : args) {
      System.out.println("arg: " + arg);
    }
  }
}

$ pack build jcli --builder gcr.io/buildpacks/builder:v1
...
$ docker run --rm jcli arg1 arg2 arg3
arg: arg1
arg: arg2
arg: arg3
```

**Comment by adamzr** [comment]
Thanks that's good to know.

I found that for Java I could use `JDK_JAVA_OPTIONS` and it got picked up correctly. I'll stick with that for now.
